remote_theme: just-the-docs/just-the-docs

color_scheme: dark

nav_order: 1
has_children: true
title: "Black Ice"

kramdown:
  parse_block_html: true

aux_links:
  "GitHub":
    - "https://github.com/TeamFrozenCodeFTC/Black-Ice-Path-Follower"
  "Team Website":
    - "https://sites.google.com/view/frozencodeftc/home"
